name: Nightly build

on:
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC
  workflow_dispatch:

jobs:
  build-archetype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java SE 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8

      - name: Build Archetype
        run: |
          mvn clean install --file archetype/pom.xml
          
          cat archetype/target/classes/archetype-resources/pom.xml
          
          bash -c pwd
          
          bash -c find          

