name: Nightly build

on:
  push:
  workflow_dispatch:

jobs:
  build-archetype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java SE 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Archetype
        run: |
          mvn clean install --file archetype/pom.xml
          
          head archetype/target/classes/archetype-resources/pom.xml
          
          bash -c pwd
          
          bash -c find          

