name: Nightly build

on:
  push:
  workflow_dispatch:

jobs:
  build-archetype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java SE 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8

      - name: Build Archetype
        run: |
          mvn -B clean install --file archetype/pom.xml
          
          cat archetype/target/classes/archetype-resources/pom.xml
          
          bash -c pwd
          
          bash -c find          

